### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by jose-amat** [sassoftware/viya-apps-serverless-score#1]
I am using a Viya instance in AWS EC2.

I had to load the ASTORE model in the caslib "CASUSER(sasdemo01)".

This is my serverless.yml file:
![image](https://user-images.githubusercontent.com/36350856/85876395-08e98100-b7ac-11ea-9b50-622901e7d5f3.png)

There is no problem when I execute the serverless deploy command:
![image](https://user-images.githubusercontent.com/36350856/85876535-3d5d3d00-b7ac-11ea-8675-96f1108dc371.png)

The problem happens when I enter the input values within the application:
![image](https://user-images.githubusercontent.com/36350856/85876683-7695ad00-b7ac-11ea-8ae8-f7d11791b21f.png)

I also had to change the value of CASLIB within the loan.html file
![image](https://user-images.githubusercontent.com/36350856/85876832-a775e200-b7ac-11ea-80e2-2837a2f66ec0.png)

Any idea what might be going on?

**Comment by devaKumaraswamy** [comment]
@jose-amat  - will need more information than what you have sent. Here are  some suggestions for debugging:

- check the logs to see if any errors exist there - that might give you some clues
- make sure the viya server you have setup on ec2 takes http
- make sure your setup is complete( see https://github.com/sassoftware/restaf/wiki/Configuring-SAS-Viya-AWS-Quick-Start-for-serverless-functions). - this might apply to your situation.
- run it locally via serverless cli to see what is going on. alternatively you can run via POSTMAN.
- feel free to contact me
Deva
PS: you can just specify casuser - no need for the qualified casuser(...)

**Comment by jose-amat** [comment]
Just to close this issue: With the help of Deva we saw that the problem was that the Score function was not finding the file GRADIENT_BOOSTING___BAD_2 within the CAS. I was using the swat package to load the table inside the CAS.

The workaround to fix it was loading the file manually using the SAS Environment Manager.

After that the Score function worked perfectly.

![image](https://user-images.githubusercontent.com/36350856/86279399-543acf80-bbb0-11ea-8aeb-3d7a53af445e.png)

PS: we use Postman to request the Score function
